### ISSUE TITLE
Restock

### ISSUE THREAD

**Issue by kiljorn1109** [ilyarolf/AiogramShopBot#42]
any way to specify the item quantity for restock? i didn t find it in the code and it just replenishes everything by 1.

**Comment by kiljorn1109** [comment]
Well the stock keeping of it, after i enter the categories and subs for it i don t have an option for quantity or somethjng else but i have in the /admin the restock announcement option

**Comment by ilyarolf** [comment]
@kiljorn1109 To be honest, I don't understand what you want. Can you please explain what you expect to get from the bot, and what you actually get. Also describe what you do to get it.

**Comment by kiljorn1109** [comment]
So the git i cloned, i have the bot the contact cards the products, everything but in the products.json let s say i don t have the quantity of the specified product, but when i enter from a buyer account i see that i have a quantity, is there any way i could set that ? 
<img width="267" alt="Screenshot 2024-06-27 at 19 24 21" src="https://github.com/ilyarolf/AiogramShopBot/assets/74836003/19b5108a-bd6c-40b3-949c-7b1eca79f90f">

**Comment by ilyarolf** [comment]
If you want to set the quantity of items manually, there is no such functionality. The quantity of items means all items that have the "is_sold == False" field. If you plan to sell items that you have in infinite quantity, it will be easier to generate 999+ such records, and add "contact admin" or something like that to the "private_data" field.
```
{
	"items": [
		{
			"category": "Category#1",
			"subcategory": "Subcategory#1",
			"price": 50,
			"description": "Mocked description",
			"private_data": "Contact Admin"
		},
		{
			"category": "Category#1",
			"subcategory": "Subcategory#1",
			"price": 50,
			"description": "Mocked description",
			"private_data": "Contact Admin"
		}
		........... 999+ records
		,
		{
			"category": "Category#1",
			"subcategory": "Subcategory#1",
			"price": 50,
			"description": "Mocked description",
			"private_data": "Contact Admin"
		}
	]
}
```

**Comment by ilyarolf** [comment]
@kiljorn1109 Is your issue still relevant?

**Comment by baz0okq** [comment]
Sorry for placing that comment here, just dont want create new issue. Dont have any option to get you. Can you please answer me in tg!

**Comment by Dimu001** [comment]
What do you mean ?

**Comment by baz0okq** [comment]
Few months ago we speak about business in telegram. Can you answer me there?

**Comment by Dimu001** [comment]
Can you reply on telegram

I can not find you

**Comment by baz0okq** [comment]
Hmm, maybe you have new one. It shows that you was online " last seen within a month "
Try add me https://t.me/didluh

**Comment by ilyarolf** [comment]
@baz0okq Hi, I replied to you on telegram on August 9 at 8:27 UTC. @Dimu001 is an imposter

**Comment by 6R1M5L07H** [comment]
Refreshing this discussion: would it be okay to raise this as feature request? Let's say you have developed a software and want to offer 20 implementation services for the next months. All services are identical from the costumer's perspective while the logic of this shop is to have each service offering unique and identifiable, e.g. to keep track of a customer's purchase history. As shop admin, it would be convenient to have an additional field "quantity" available so that you can simply define one article (o.e. subcategory) once but you can add the same article n times according to the field "quantity". This would make the handling of adding articles to the shop as it is implemented now a bit easier for the admin.

Maybe this would be a good feature request.
